version: '3'

services:
  catalog-server:
    build:
      context: .
      target: production
    volumes:
      - ./src/catalog-service:/app/src/catalog-service:ro
      - ./src/nginx:/app/src/nginx:ro
    ports:
      - '3005:3005'
    environment:
      - PORT=3005
      - NODE_ENV=production
  
  order-server:
    build:
      context: .
      target: production1
    volumes:
      - ./src/order-service:/app/src/order-service:ro
      - ./src/nginx:/app/src/nginx:ro
    ports:
      - '3006:3006'
    environment:
      - PORT=3006
      - NODE_ENV=production1
    depends_on:
      - nginx

 
  nginx:
    image: nginx:stable-alpine
    ports:
      - '8083:80'
    volumes:
      - ./src/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - catalog-server

 





    